jobs:
  - job: test
    steps:
      - checkout: self

      - task: UseNode@1
        inputs:
          version: '20.x'

      - script: |
          npm install
          npm test
        displayName: "Run tests"
