jobs:
  - job: test
    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          version: "1.25.0"

      - script: |
          npm install
          npm test
        displayName: "Run tests"
