name: Auto Commit Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:         # Allow manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make a dummy change
        run: |
          echo "Last run: $(date)" > heartbeat.txt

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto commit at $(date)" || echo "No changes to commit"
          git push origin main
