name: static

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check code formatting
        run: npx prettier --check .
